# SPECIFYING THE COMPILER
CXX = g++

# SPECIFYING THE COMPILER FLAGS
CXXFLAGS = -std=c++17

# SPECIFYING THE TARGET
TARGET = main

# SPECIFYING THE DEFAULT RULE OF COMPILATION
$(TARGET): main.cpp
	$(CXX) $(CXXFLAGS) main.cpp -o $(TARGET)

# SPECIFYING THE CLEAN RULE
clean:
	rm -rf $(TARGET)
